
class Strings {
  static const String mapTileSprite = 'tiles.png';
  static const List<String> treeSprites = [
    'trees/tree_blocks_dark_NE.png',
    // 'trees/tree_blocks_fall_NE.png',
    // 'trees/tree_blocks_NE.png',
    // 'trees/tree_cone_dark_NE.png',
    // 'trees/tree_cone_fall_NE.png',
    // 'trees/tree_cone_NE.png',
    'trees/tree_default_dark_NE.png',
    // 'trees/tree_default_fall_NE.png',
    // 'trees/tree_default_NE.png',
    // 'trees/tree_detailed_dark_NE.png',
    // 'trees/tree_detailed_fall_NE.png',
    // 'trees/tree_detailed_NE.png',
    // 'trees/tree_fat_darkh_NE.png',
    // 'trees/tree_fat_fall_NE.png',
    // 'trees/tree_fat_NE.png',
    // 'trees/tree_oak_dark_NE.png',
    // 'trees/tree_oak_fall_NE.png',
    // 'trees/tree_oak_NE.png',
    // 'trees/tree_palm_NE.png',
    // 'trees/tree_palmBend_NE.png',
    // 'trees/tree_palmDetailedShort_NE.png',
    // 'trees/tree_palmDetailedTall_NE.png',
    // 'trees/tree_palmShort_NE.png',
    // 'trees/tree_palmTall_NE.png',
    // 'trees/tree_pineDefaultA_NE.png',
    // 'trees/tree_pineDefaultB_NE.png',
    // 'trees/tree_pineGroundA_NE.png',
    // 'trees/tree_pineGroundB_NE.png',
    // 'trees/tree_pineRoundA_NE.png',
    // 'trees/tree_pineRoundB_NE.png',
    // 'trees/tree_pineRoundC_NE.png',
    // 'trees/tree_pineRoundD_NE.png',
    // 'trees/tree_pineRoundE_NE.png',
    // 'trees/tree_pineRoundF_NE.png',
    // 'trees/tree_pineSmallA_NE.png',
    // 'trees/tree_pineSmallB_NE.png',
    // 'trees/tree_pineSmallC_NE.png',
    // 'trees/tree_pineSmallD_NE.png',
    // 'trees/tree_pineTallA_detailed_NE.png',
    // 'trees/tree_pineTallA_NE.png',
    // 'trees/tree_pineTallB_detailed_NE.png',
    // 'trees/tree_pineTallB_NE.png',
    // 'trees/tree_pineTallC_detailed_NE.png',
    // 'trees/tree_pineTallC_NE.png',
    // 'trees/tree_pineTallD_detailed_NE.png',
    // 'trees/tree_pineTallD_NE.png',
    // 'trees/tree_plateau_dark_NE.png',
    // 'trees/tree_plateau_fall_NE.png',
    // 'trees/tree_plateau_NE.png',
    // 'trees/tree_simple_dark_NE.png',
    // 'trees/tree_simple_fall_NE.png',
    // 'trees/tree_simple_NE.png',
    // 'trees/tree_small_dark_NE.png',
    // 'trees/tree_small_fall_NE.png',
    // 'trees/tree_small_NE.png',
    // 'trees/tree_tall_dark_NE.png',
    // 'trees/tree_tall_fall_NE.png',
    // 'trees/tree_tall_NE.png',
    // 'trees/tree_thin_dark_NE.png',
    // 'trees/tree_thin_NE.png',
  ];

}